"""Prompt Profile 定义：每个模式只加载明确列出的模块。

替代全量组合 + 黑名单过滤，让 Prompt 组合完全可预测。
"""

PROMPT_PROFILES: dict[str, tuple[str, ...]] = {
    "route_initial": (
        "runtime_boundary",
        "safety_injection_resistance",
        "production_security",
        "test_mode_info",
        "route_initial",
        "tool_list",
        "anti_roleplay",
    ),
    "route_after_plan": (
        "runtime_boundary",
        "safety_injection_resistance",
        "production_security",
        "test_mode_info",
        "route_after_plan",
        "tool_list",
        "anti_roleplay",
    ),
    "route_after_implement": (
        "runtime_boundary",
        "safety_injection_resistance",
        "production_security",
        "test_mode_info",
        "route_after_implement",
        "tool_list",
        "anti_roleplay",
    ),
    "route_after_validate": (
        "runtime_boundary",
        "safety_injection_resistance",
        "production_security",
        "test_mode_info",
        "route_after_validate",
        "tool_list",
        "anti_roleplay",
    ),
    "plan": (
        "runtime_boundary",
        "safety_injection_resistance",
        "production_security",
        "test_mode_info",
        "project_rules",
        "plan_workflow",
        "plan_spec",
        "skill_context",
        "task_context",
        "tool_list",
        "anti_roleplay",
    ),
    "implement": (
        "runtime_boundary",
        "safety_injection_resistance",
        "production_security",
        "test_mode_info",
        "project_rules",
        "implement_workflow",
        "validate_feedback",
        "artifact_output_contract",
        "output_contract",
        "skill_context",
        "task_context",
        "tool_list",
        "anti_roleplay",
    ),
    "validate": (
        "runtime_boundary",
        "safety_injection_resistance",
        "production_security",
        "test_mode_info",
        "project_rules",
        "validate_workflow",
        "task_context",
        "tool_list",
        "anti_roleplay",
    ),
}
