# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import platform_service_pb2 as platform__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in platform_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlatformServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModelConfig = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/GetModelConfig',
                request_serializer=platform__service__pb2.GetModelConfigRequest.SerializeToString,
                response_deserializer=platform__service__pb2.GetModelConfigResponse.FromString,
                _registered_method=True)
        self.ResolveRuntimeModelBundle = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/ResolveRuntimeModelBundle',
                request_serializer=platform__service__pb2.ResolveRuntimeModelBundleRequest.SerializeToString,
                response_deserializer=platform__service__pb2.ResolveRuntimeModelBundleResponse.FromString,
                _registered_method=True)
        self.BuildVueProject = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/BuildVueProject',
                request_serializer=platform__service__pb2.BuildVueProjectRequest.SerializeToString,
                response_deserializer=platform__service__pb2.BuildVueProjectResponse.FromString,
                _registered_method=True)
        self.DeployApp = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/DeployApp',
                request_serializer=platform__service__pb2.DeployAppRequest.SerializeToString,
                response_deserializer=platform__service__pb2.DeployAppResponse.FromString,
                _registered_method=True)
        self.CompleteAgentRun = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/CompleteAgentRun',
                request_serializer=platform__service__pb2.CompleteAgentRunRequest.SerializeToString,
                response_deserializer=platform__service__pb2.CompleteAgentRunResponse.FromString,
                _registered_method=True)
        self.CreateAppVersion = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/CreateAppVersion',
                request_serializer=platform__service__pb2.CreateAppVersionRequest.SerializeToString,
                response_deserializer=platform__service__pb2.CreateAppVersionResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/GetChatHistory',
                request_serializer=platform__service__pb2.GetChatHistoryRequest.SerializeToString,
                response_deserializer=platform__service__pb2.GetChatHistoryResponse.FromString,
                _registered_method=True)
        self.UpdateAppCodeGenType = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/UpdateAppCodeGenType',
                request_serializer=platform__service__pb2.UpdateAppCodeGenTypeRequest.SerializeToString,
                response_deserializer=platform__service__pb2.UpdateAppCodeGenTypeResponse.FromString,
                _registered_method=True)
        self.GetAppDetail = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/GetAppDetail',
                request_serializer=platform__service__pb2.GetAppDetailRequest.SerializeToString,
                response_deserializer=platform__service__pb2.GetAppDetailResponse.FromString,
                _registered_method=True)
        self.GetUserInfo = channel.unary_unary(
                '/com.adcage.acaicodefree.PlatformService/GetUserInfo',
                request_serializer=platform__service__pb2.GetUserInfoRequest.SerializeToString,
                response_deserializer=platform__service__pb2.GetUserInfoResponse.FromString,
                _registered_method=True)


class PlatformServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveRuntimeModelBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildVueProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteAgentRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAppVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAppCodeGenType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelConfig,
                    request_deserializer=platform__service__pb2.GetModelConfigRequest.FromString,
                    response_serializer=platform__service__pb2.GetModelConfigResponse.SerializeToString,
            ),
            'ResolveRuntimeModelBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveRuntimeModelBundle,
                    request_deserializer=platform__service__pb2.ResolveRuntimeModelBundleRequest.FromString,
                    response_serializer=platform__service__pb2.ResolveRuntimeModelBundleResponse.SerializeToString,
            ),
            'BuildVueProject': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildVueProject,
                    request_deserializer=platform__service__pb2.BuildVueProjectRequest.FromString,
                    response_serializer=platform__service__pb2.BuildVueProjectResponse.SerializeToString,
            ),
            'DeployApp': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployApp,
                    request_deserializer=platform__service__pb2.DeployAppRequest.FromString,
                    response_serializer=platform__service__pb2.DeployAppResponse.SerializeToString,
            ),
            'CompleteAgentRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteAgentRun,
                    request_deserializer=platform__service__pb2.CompleteAgentRunRequest.FromString,
                    response_serializer=platform__service__pb2.CompleteAgentRunResponse.SerializeToString,
            ),
            'CreateAppVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAppVersion,
                    request_deserializer=platform__service__pb2.CreateAppVersionRequest.FromString,
                    response_serializer=platform__service__pb2.CreateAppVersionResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=platform__service__pb2.GetChatHistoryRequest.FromString,
                    response_serializer=platform__service__pb2.GetChatHistoryResponse.SerializeToString,
            ),
            'UpdateAppCodeGenType': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAppCodeGenType,
                    request_deserializer=platform__service__pb2.UpdateAppCodeGenTypeRequest.FromString,
                    response_serializer=platform__service__pb2.UpdateAppCodeGenTypeResponse.SerializeToString,
            ),
            'GetAppDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppDetail,
                    request_deserializer=platform__service__pb2.GetAppDetailRequest.FromString,
                    response_serializer=platform__service__pb2.GetAppDetailResponse.SerializeToString,
            ),
            'GetUserInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserInfo,
                    request_deserializer=platform__service__pb2.GetUserInfoRequest.FromString,
                    response_serializer=platform__service__pb2.GetUserInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.adcage.acaicodefree.PlatformService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.adcage.acaicodefree.PlatformService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlatformService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/GetModelConfig',
            platform__service__pb2.GetModelConfigRequest.SerializeToString,
            platform__service__pb2.GetModelConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveRuntimeModelBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/ResolveRuntimeModelBundle',
            platform__service__pb2.ResolveRuntimeModelBundleRequest.SerializeToString,
            platform__service__pb2.ResolveRuntimeModelBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildVueProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/BuildVueProject',
            platform__service__pb2.BuildVueProjectRequest.SerializeToString,
            platform__service__pb2.BuildVueProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/DeployApp',
            platform__service__pb2.DeployAppRequest.SerializeToString,
            platform__service__pb2.DeployAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteAgentRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/CompleteAgentRun',
            platform__service__pb2.CompleteAgentRunRequest.SerializeToString,
            platform__service__pb2.CompleteAgentRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAppVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/CreateAppVersion',
            platform__service__pb2.CreateAppVersionRequest.SerializeToString,
            platform__service__pb2.CreateAppVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/GetChatHistory',
            platform__service__pb2.GetChatHistoryRequest.SerializeToString,
            platform__service__pb2.GetChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAppCodeGenType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/UpdateAppCodeGenType',
            platform__service__pb2.UpdateAppCodeGenTypeRequest.SerializeToString,
            platform__service__pb2.UpdateAppCodeGenTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/GetAppDetail',
            platform__service__pb2.GetAppDetailRequest.SerializeToString,
            platform__service__pb2.GetAppDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.PlatformService/GetUserInfo',
            platform__service__pb2.GetUserInfoRequest.SerializeToString,
            platform__service__pb2.GetUserInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
